### ISSUE TITLE
Incorrect rendering of long blocks of text

### ISSUE THREAD

**Issue by CatcherITGF** [efosamark/Uberhand-Overlay#109]
- It appears in the Help text blocks and in the Kip Management if the amount of text goes beyond the page
- Scrolling cannot be controlled from the buttons

![2024-08-27_18-22-56](https://github.com/user-attachments/assets/f4630cc8-dc04-412e-9bfd-cd633b8f3d72)

**Comment by IrneRacoonovich** [comment]
For the scrolling issue I've created a separate item: #120
