### ISSUE TITLE
Feature Request: kip management labels

### ISSUE THREAD

**Issue by CatcherITGF** [efosamark/Uberhand-Overlay#112]
The ability to display json value instead of pure numbers from the kip. Following the example of how it is implemented in the Wizard.

![2024-08-27_18-47-26](https://github.com/user-attachments/assets/8be6b670-3327-4f1f-963c-893f7e55f11f)
![2024-08-27_18-49-55](https://github.com/user-attachments/assets/2dab8308-f5b7-4d56-a091-cade4c8c39d1)

**Comment by efosamark** [comment]
Code complete, awaiting release
