### ISSUE TITLE
The problem with negative values in kip management

### ISSUE THREAD

**Issue by CatcherITGF** [efosamark/Uberhand-Overlay#115]
Shown in the screenshots. You can test it in RAM -> EMC DVB Shift -> any negative value.

![2024-08-27_20-06-54](https://github.com/user-attachments/assets/6a18d08c-3463-41e3-9f01-de6bdd9c8c48)
![2024-08-27_20-06-57](https://github.com/user-attachments/assets/124338fa-1bfc-4c46-a617-cc397503ecc6)

[SC Wizard.zip](https://github.com/user-attachments/files/16766400/SC.Wizard.zip)

**Comment by efosamark** [comment]
Code complete, awaiting release
