### ISSUE TITLE
Feature Request: Splitting the text by console type when displaying help

### ISSUE THREAD

**Issue by CatcherITGF** [efosamark/Uberhand-Overlay#129]
The ability to use `; Mariko` `; Erista` in the help texts

**Comment by CatcherITGF** [comment]
This task can also be solved by introducing a selection of menu items inside the help element:

-Mariko
-Erista

It can also be useful for implementing multiple guides within a single menu item.:

- General guide
- Stability guide
- Testing the guide

**Comment by efosamark** [comment]
If you want to display text from the source - use text_source <path/to/file> command.
This way you have control on what is displayed and when.
