### ISSUE TITLE
Request for Proper Attribution of "Ultrahand Overlay" Fork

### ISSUE THREAD

**Issue by ppkantorski** [efosamark/Uberhand-Overlay#25]
Dear Efosamark, 

I hope this message finds you well. I recently became aware that you have forked my project, "Ultrahand Overlay," and created a fork named "Uberhand Overlay." While I appreciate your interest in the project and your contributions, I noticed that the fork lacks proper attribution to the original creator.

As the original author of "Ultrahand Overlay," I would like to kindly request that you update your forked project to include the necessary attribution to me, ppkantorski (b0rd2dEAth), the original creator. Proper attribution is a requirement of the Creative Commons Attribution-NonCommercial (CC BY-NC) license under which "Ultrahand Overlay" is released.

The required attribution should include:

- Clearly mentioning the project's name, "Ultrahand Overlay," as the source.
- Providing my name or username, ppkantorski (b0rd2dEAth), as the original author.
- Including a link to the original "Ultrahand Overlay" repository (if applicable).

This attribution not only ensures compliance with the CC BY-NC license but also acknowledges the effort and contribution made by the original creator. It fosters a collaborative and respectful atmosphere within the open-source community.

I am more than willing to assist you in adding the required attribution, should you need any guidance or support in this matter. My goal is to encourage collaboration and maintain transparency within the development community.

Your understanding and cooperation in this regard would be greatly appreciated. I look forward to seeing the updated "Uberhand Overlay" fork with the proper attribution to "Ultrahand Overlay" and myself, ppkantorski (b0rd2dEAth).

If you have any questions or require further assistance, please do not hesitate to reach out to me. I am here to help and support your contributions to the project.

Thank you for your attention to this matter, and I am confident that we can resolve this issue amicably.

Best regards,
ppkantorski (b0rd2dEAth)
Original Author of "Ultrahand Overlay"

**Comment by ppkantorski** [comment]
I apologize for the scripted response, I do see that some of the CC-BY-NC requirements have been implemented.  But it would be appreciated still if you cite me under contributors where necessary.

**Comment by i3sey** [comment]
Hello, I am one of the developers of this project. We lacked some features specific to the overclocking community, so we made our own fork. We apologize for not paying attention to your attribution. 
Please note that you are listed as the author of the original repository ("forked from" github label) and on the main page of the wiki. All changes are listed as commit history on the same github. 
Also, please indicate where we can best indicate your authorship.

**Comment by ppkantorski** [comment]
Appreciate the quick response. Just a couple locations would be ideal.  For instance (https://efosamark.github.io/Uberhand-Overlay/about/) and  (https://github.com/efosamark/Uberhand-Overlay/blob/main/Makefile#L41), where it says you three as the current contributors, it would be appreciated if you would just squeeze my name in there too.

As for the new hex functions that I see you guys have added, I can add those to the actual source code over time if you guys wanted (contributions are welcome).  No one so far has asked me about improving hex functions or potential pull requests surrounding them, so it is interesting seeing how you guys are using it.  I have no problems with your fork, just keep me in contributors where you can.  Thanks again.

**Comment by efosamark** [comment]
HI @ppkantorski 

We added more mentions and with that are closing the issue. We will probably shift things around a bit, however the mentions will remain as seen in the merged PR. Should you have any questions or concerns - please, let us know.

Thanks!
