### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by Godlux** [efosamark/Uberhand-Overlay#42]
Using Uberhand 2.0.1 can't update to latest, even by updating 4IFIR from AIO.
"No updates" says in menu. Sometimes it opens, but prints "FAIL" after trying update.

**Comment by i3sey** [comment]
Please provide /config/uberhand/log.txt file

**Comment by Godlux** [comment]
[log.txt](https://github.com/efosamark/Uberhand-Overlay/files/13364197/log.txt)

**Comment by Godlux** [comment]
Данный файл отсутствует. Есть только папки:
About
Backup
Full Assist
Help
Manual Configuration

И файл:
config.ini

**Comment by i3sey** [comment]
хорошо, что в файле config.ini?

**Comment by Godlux** [comment]
-- Did it work?
[*Yes ;; VDD2 Mode]
; Mariko
catch_errors
json_source '/switch/.packages/4IFIR Wizard/Full Assist/json/3VDD2.json' name
hex-by-cust-offset /atmosphere/kips/loader.kip 36 {json_source(*,hex)}
cp '/switch/.packages/4IFIR Wizard/Full Assist/inis/4VDDQ.ini' '/switch/.packages/4IFIR Wizard/config.ini'
reboot

[*No ;; CPU VMAX Mode]
catch_errors
json_mark_cur_kip '/switch/.packages/4IFIR Wizard/Full Assist/json/2CPU_VMAX.json' name 28
hex-by-cust-offset /atmosphere/kips/loader.kip 28 {json_mark_cur_kip(*,hex)}
; cp '/switch/.packages/4IFIR Wizard/Full Assist/inis/gpu-ram.ini' '/switch/.packages/4IFIR Wizard/config.ini'
reboot

-- Stop the process
[Save and stop]
cp '/switch/.packages/4IFIR Wizard/Full Assist/inis/Start.ini' '/switch/.packages/4IFIR Wizard/config.ini'
rename '/switch/.packages/4IFIR Wizard/Full Assist/!config.ini' '/switch/.packages/4IFIR Wizard/Full Assist/config.ini' 
rename '/switch/.packages/4IFIR Wizard/Manual Configuration/!config.ini' '/switch/.packages/4IFIR Wizard/Manual Configuration/config.ini' 
rename '/switch/.packages/4IFIR Wizard/Backup/!config.ini' '/switch/.packages/4IFIR Wizard/Backup/config.ini' 
rename '/switch/.packages/4IFIR Wizard/About/!config.ini' '/switch/.packages/4IFIR Wizard/About/config.ini' 
back

**Comment by efosamark** [comment]
Привет.

Останови фулл ассист и обнови визард.
