### ISSUE TITLE
The uberhand menu will not open

### ISSUE THREAD

**Issue by MintyHeal** [efosamark/Uberhand-Overlay#64]
After logging into an application, launching the uberhand and exiting through the home button, the uberhand stops opening

**Comment by efosamark** [comment]
Hi. We have fix in place for this, that will be released with the next update.
For now - when this happens, use the default Tesla key combo (L+RS+DDOWN) to open the menu for the first time after sleep

**Comment by MintyHeal** [comment]
Thanks

**Comment by MintyHeal** [comment]
Thanks
