### ISSUE TITLE
Crash happened after other overlays is opened and press home button in game

### ISSUE THREAD

**Issue by WE1ZARD** [efosamark/Uberhand-Overlay#78]
**Uberhand version 2.1.2**

Tested overlay list on AMS 1.6.2 (HOS 17.01, HOS 16.10):
- EdiZon 1.0.7
- FPSLocker 1.2.6a
- ReverseNX-RT 2.0.0
- (status monitor v1.0.3a no effected)
- Sysmodules 1.2.2
- sys-clk 2.0.0 b7

It's unable to toggle uberhand after crash happened.

**Reproduce method**:
1. toggle uberhand and open any overlays above in any game.
2. press home button will cause uberhand crashed.
3. **reboot** or use **hekate toolbox** `>background services >tesla >off  >on` could be solved temporary.

**Comment by efosamark** [comment]
Hello.
Have you tried using the default tesla key combo? (L+RT(R3)+DDOWN)

**Comment by WE1ZARD** [comment]
ah, i can actually toggle it with default tesla key combo, so this only happen to custom key combo.
BIG THANKS for your help!!!

**Comment by efosamark** [comment]
No problem. This issue is already fixed in the code and is awaiting release.
Will work with the Uberhand key combo all the time from 2.1.3.

Stay tuned :)
