### ISSUE TITLE
Uberhand adds a space before and after the = sign.

### ISSUE THREAD

**Issue by h4ck3rmn2137** [efosamark/Uberhand-Overlay#88]
Uberhand when changing values in the INI file, adds a space before the = sign and after. This causes the game to not read the settings from the file correctly when editing INI files in SKYRIM. 

An example function from the created package.

Config.ini file:
`[*FXAA]
catch_errors
json_mark_cur_ini '/switch/.packages/Skyrim/json/FXAA.json' name '/atmosphere/contents/01000A10041EA000/romfs/Skyrim.ini' Display bFXAAEnabled
set-ini-val '/atmosphere/contents/01000A10041EA000/romfs/Skyrim.ini' Display bFXAAEnabled {json_source(*,value)}
back`

FXAA.json file:
`[
  {
    "name": "ON",
    "value": "1"
  },
  {
    "name": "OFF",
    "value": "0"
  }
]`

I think the problem is here:
`void writeIniFile(const std::string& filename, const IniSectionInput& iniData) {
    std::ofstream outFile(filename);
    for (const auto& [section, kvPairs] : iniData) {
        outFile << "[" << section << "]\n";
        for (const auto& [key, value] : kvPairs) {
            outFile << key << " = " << value << "\n";
        }
        outFile << "\n";
    }
    outFile.close();
}`

specifically this line:

`outFile << key << " = " << value << "\n";`

**Comment by i3sey** [comment]
sorry for the long wait, it was fixed in 2.1.5 #93
