### ISSUE TITLE
[Request] homebrew nro version

### ISSUE THREAD

**Issue by cucholix** [efosamark/Uberhand-Overlay#89]
Port it to run as a homebrew nro version.

**Comment by IrneRacoonovich** [comment]
What for? Please provide a use case.

**Comment by cucholix** [comment]
Uberhand overlay is 1.52mb, being a replacement for official ovlmenu.ovl which is only 153kb, it consumes the memory pool considerably when you use it in conjuntion with other sys-modules. I have 4 sys-modules actives and opening ovlmenu often result in ams crash.

**Comment by IrneRacoonovich** [comment]
So how an overlay launcher would help while not being an overlay itself? I can't understand what task you're trying to solve with this proposal.

In any case, if you really want to launch it as a homebrew you can just rename the `ovlmenu.ovl` into `ovlmenu.nro` and put it into the `/switch` folder. In the end every overlay is literally just a homebrew with a different extension.
